In [ ]:
test1 = [1,2,3]
print(type(test1))


<class 'list'>


In [ ]:
import numpy as np
test2 = np.array([1,2,3])
print(type(test2))

<class 'numpy.ndarray'>


In [ ]:
a = np.array([1,2,4,5])
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a[0])

[1 2 4 5]
<class 'numpy.ndarray'>
(4,)
4
1


In [ ]:
b = np.array([[1],[2],[4],[5]])
print(b)
print(b.shape)
print(b.size)

[[1]
 [2]
 [4]
 [5]]
(4, 1)
4


In [ ]:
# arange (start,end,step)

print(np.arange(1,101))
print(np.arange(1,101,2))
print(np.arange(0,101,2))
print(np.arange(10,0,-1))



[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
y = np.linspace(1,100)

print(y)
print(y.shape)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
(50,)


In [ ]:
z = np.linspace(1,100,100)#to get 100 elements
# add 3rd argument as 100
print(z)
print(z.shape)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
(100,)


In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [ ]:
#The code print(np.ones(5)) generates and prints a NumPy array of ones of shape (5,). This means that the array has 5 elements, all of which are equal to 1.

#The np.ones() function is a NumPy function that creates a new array of given shape and type, filled with ones. The function takes two arguments:


# Generating matrices
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
# To get the va;ues in integer add dtype = int
g = np.ones((3,1), dtype = int)
print(g)

[[1]
 [1]
 [1]]


In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.eye(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c = np.zeros((2,3),dtype=int)
print(c)

[[0 0 0]
 [0 0 0]]


In [ ]:
d = np.random.rand(5)
print(d)


[0.92475502 0.11591877 0.26604504 0.42127613 0.76251594]


In [ ]:
D = np.random.rand(3,2)
print(D)

[[0.879313   0.68013863]
 [0.54022451 0.5645546 ]
 [0.16656303 0.66853472]]


In [ ]:
w = np.random.rand(4,4)
print(w)

[[0.90066969 0.25754429 0.2247429  0.90719561]
 [0.04267715 0.64858861 0.3728223  0.05497205]
 [0.12747634 0.80887435 0.42293348 0.750425  ]
 [0.01979318 0.8832041  0.84069725 0.82585285]]


In [ ]:
np.random.seed(1)
print(np.random.rand(5))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]


In [ ]:
d = np.random.randn(5)
print(d)

[-1.10593508 -1.65451545 -2.3634686   1.13534535 -1.01701414]


In [ ]:
D = np.random.randn(3,2)

In [ ]:
d = np.random.randint(1,100)
print(d)



10


In [ ]:
d = np.random.randint(1,100,10)
print(d)

[89 14 48 73 31 72  4 71 22 50]


In [ ]:
D = np.random.randint(1,100,(3,2))
print(D)

[[58  4]
 [69 25]
 [44 77]]


In [ ]:
X = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

print(X[2,3]) #access elemts in 3rd row and 4th colum
print(X[2,:]) # access 3rd row
print(X[:,3]) # access 4th colum

12
[ 9 10 11 12]
[ 4  8 12 16]


In [ ]:
y= X[1:3,1:3].copy()# here , Y is a view of X
print(y)


[[ 6  7]
 [10 11]]


In [ ]:
y [:,:] = 0
print(y)

[[0 0]
 [0 0]]


In [ ]:
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# Fancy Indexing / Boolean Valued Indexing

In [ ]:
a = np.linspace(0,1,11)
print(a)
print(a > 0.5) # cheak whether the values in a aare greater than 0.5
print(a[a>0.5]) # retrieve only values greater than 0.5

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[False False False False False False  True  True  True  True  True]
[0.6 0.7 0.8 0.9 1. ]
